const monthNames=['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des'];
const sppgNames=['Dadali','Lw. Liang 1','Lw. Liang 2','Lw. Liang 3','Cigudeg 1','Cigudeg 2','Jasinga 1','Jasinga 2','Pasir Angin 1','Cipayung','Cibogo','Tanjungsari 1','Tanjungsari 2','Klapanunggal 1','Klapanunggal 2','Rumpin 1','Rumpin 2','Tanjungkerta','Kuningan 1','Kuningan 2','Garut 1','Garut 2','Cimanggu','Cabang Bungin 1','Cabang Bungin 2'];
const seed={
  meta:{sppg:'NAMA SPPG',period:'2026-06'},
  assets:[{assetNo:'AST-PURI-DDL-001',name:'Laptop Finance 01',location:'HO Lt.2',pic:'Rina',status:'Sesuai',condition:'Baik'}],
  facilities:[{name:'Ruang Meeting',standard:6,actual:6,condition:'Baik'},{name:'Toilet',standard:12,actual:12,condition:'Baik'},{name:'Pantry',standard:4,actual:4,condition:'Baik'},{name:'Area Parkir',standard:80,actual:78,condition:'Baik'}],
  maintenance:[{month:'Jan',scheduled:20,realized:20,ticket:'MT-001',start:'2026-01-05',finish:'2026-01-06',sla:3},{month:'Feb',scheduled:21,realized:21,ticket:'MT-002',start:'2026-02-05',finish:'2026-02-07',sla:3},{month:'Mar',scheduled:22,realized:22,ticket:'MT-003',start:'2026-03-05',finish:'2026-03-08',sla:3},{month:'Apr',scheduled:20,realized:20,ticket:'MT-004',start:'2026-04-05',finish:'2026-04-09',sla:3},{month:'Mei',scheduled:21,realized:20,ticket:'MT-005',start:'2026-05-05',finish:'2026-05-10',sla:3},{month:'Jun',scheduled:22,realized:22,ticket:'MT-006',start:'2026-06-05',finish:'2026-06-06',sla:3},{month:'Jul',scheduled:20,realized:20,ticket:'MT-007',start:'2026-07-05',finish:'2026-07-07',sla:3},{month:'Agu',scheduled:21,realized:21,ticket:'MT-008',start:'2026-08-05',finish:'2026-08-08',sla:3},{month:'Sep',scheduled:22,realized:22,ticket:'MT-009',start:'2026-09-05',finish:'2026-09-09',sla:3},{month:'Okt',scheduled:20,realized:20,ticket:'MT-010',start:'2026-10-05',finish:'2026-10-10',sla:3},{month:'Nov',scheduled:21,realized:21,ticket:'MT-011',start:'2026-11-05',finish:'2026-11-06',sla:3},{month:'Des',scheduled:22,realized:22,ticket:'MT-012',start:'2026-12-05',finish:'2026-12-07',sla:3},{month:'-',scheduled:0,realized:0,ticket:'MT-013',start:'2026-12-08',finish:'2026-12-11',sla:3},{month:'-',scheduled:0,realized:0,ticket:'MT-014',start:'2026-12-20',finish:'',sla:3}],
  legality:[{document:'NIB',expiry:'2028-12-31'},{document:'Sertifikat Domisili Gedung',expiry:'2026-08-20'},{document:'PKS Security',expiry:'2026-12-31'},{document:'PKS Cleaning Service',expiry:'2026-09-15'},{document:'Izin Genset',expiry:'2027-03-01'},{document:'Sertifikat APAR',expiry:'2026-07-25'},{document:'Asuransi Gedung',expiry:'2027-01-10'},{document:'STNK Mobil Operasional 1',expiry:'2026-10-02'},{document:'STNK Mobil Operasional 2',expiry:'2026-11-18'},{document:'Kontrak Sewa Kantor',expiry:'2027-05-31'},{document:'Izin Lingkungan',expiry:'2029-01-01'}],
  budgets:[{category:'Office Supplies',budget:120000000,actual:83000000},{category:'Building Maintenance',budget:250000000,actual:197000000},{category:'Vehicle Operation',budget:180000000,actual:146000000},{category:'Security',budget:360000000,actual:180000000},{category:'Cleaning Service',budget:300000000,actual:151000000},{category:'Utility',budget:420000000,actual:238000000},{category:'Legal Renewal',budget:90000000,actual:32000000},{category:'Minor Renovation',budget:200000000,actual:125000000},{category:'Emergency Repair',budget:100000000,actual:66000000}],
  audits:[{date:'2026-06-01',area:'Lobby',auditor:'GA Supervisor',cleanliness:90,tidiness:88,lighting:92,air:89,safety:90,feasibility:88,note:'OK'},{date:'2026-06-01',area:'Ruang Kerja Lt.1',auditor:'Building Officer',cleanliness:92,tidiness:90,lighting:94,air:91,safety:91,feasibility:89,note:'OK'},{date:'2026-06-01',area:'Ruang Kerja Lt.2',auditor:'GA Supervisor',cleanliness:94,tidiness:92,lighting:96,air:93,safety:92,feasibility:90,note:'OK'},{date:'2026-06-01',area:'Meeting Room',auditor:'Building Officer',cleanliness:96,tidiness:94,lighting:92,air:95,safety:93,feasibility:91,note:'OK'},{date:'2026-06-01',area:'Pantry',auditor:'GA Supervisor',cleanliness:90,tidiness:96,lighting:94,air:89,safety:94,feasibility:92,note:'OK'},{date:'2026-06-01',area:'Toilet',auditor:'Building Officer',cleanliness:92,tidiness:88,lighting:96,air:91,safety:90,feasibility:93,note:'Perlu pengecekan ulang area toilet'},{date:'2026-06-01',area:'Parkir',auditor:'GA Supervisor',cleanliness:94,tidiness:90,lighting:92,air:93,safety:91,feasibility:88,note:'OK'},{date:'2026-06-01',area:'Utility Room',auditor:'Building Officer',cleanliness:96,tidiness:92,lighting:94,air:95,safety:92,feasibility:89,note:'OK'},{date:'2026-06-01',area:'Koridor',auditor:'GA Supervisor',cleanliness:90,tidiness:94,lighting:96,air:89,safety:93,feasibility:90,note:'OK'},{date:'2026-06-01',area:'Musholla',auditor:'Building Officer',cleanliness:92,tidiness:96,lighting:92,air:91,safety:94,feasibility:91,note:'OK'}],
  trend:[{month:'Jan',values:[.1,.4,1,.4,.7,.9,.9,.8]},{month:'Feb',values:[.1,.3,.9,.8,.8,.8,.8,.8]},{month:'Mar',values:[.05,.5,.7,.9,.99,.79,.9,.8]},{month:'Apr',values:[.6,.8,.8,1,.7,.6,1,.76]},{month:'Mei',values:[1,.9,.9,.94,.78,.99,.9,.8]}]
};
function blankRecord(name,period){return{meta:{sppg:name,period:period||new Date().toISOString().slice(0,7)},assets:[],facilities:[],maintenance:[],legality:[],budgets:[],audits:[]}}
const legacyState=JSON.parse(localStorage.getItem('gaKpiState')||'null');
let store=JSON.parse(localStorage.getItem('gaKpiStore')||'null');
if(!store){const initialName=sppgNames.includes(legacyState?.meta?.sppg)?legacyState.meta.sppg:sppgNames[0],firstRecord=legacyState||structuredClone(seed),period=firstRecord.meta?.period||'2026-06';firstRecord.meta={sppg:initialName,period};store={version:2,selectedSppg:initialName,selectedPeriod:period,records:{[initialName]:{[period]:firstRecord}}}}
if(store.records&&Object.values(store.records).some(record=>record?.assets)){const monthly={};Object.entries(store.records).forEach(([name,record])=>{const period=record.meta?.period||store.selectedPeriod||'2026-06';monthly[name]={[period]:record}});store.records=monthly;store.selectedPeriod=store.selectedPeriod||store.records[store.selectedSppg]&&Object.keys(store.records[store.selectedSppg])[0]||'2026-06'}
store.version=2;
if(!sppgNames.includes(store.selectedSppg))store.selectedSppg=sppgNames[0];store.selectedPeriod=store.selectedPeriod||new Date().toISOString().slice(0,7);
function getRecord(name=store.selectedSppg,period=store.selectedPeriod){store.records[name]??={};store.records[name][period]??=blankRecord(name,period);return store.records[name][period]}
let state=getRecord();
let currentPage='dashboard',editingIndex=null;
const schemas={
 assets:{title:'Asset Management',desc:'Inventaris, stock opname, dan kondisi aset.',button:'Tambah Asset',fields:[['assetNo','No. Asset','auto'],['name','Nama Asset','text'],['location','Lokasi','text'],['pic','PIC','text'],['status','Status','select',['Sesuai','Tidak Sesuai']],['condition','Kondisi','select',['Baik','Rusak']]],columns:[['assetNo','No. Asset'],['name','Nama Asset'],['location','Lokasi'],['pic','PIC'],['status','Status'],['condition','Kondisi']]},
 facilities:{title:'Facility Management',desc:'Standar fasilitas, ketersediaan aktual, dan kondisi.',button:'Tambah Fasilitas',fields:[['name','Fasilitas','text'],['standard','Standar','number'],['actual','Aktual','number'],['condition','Kondisi','select',['Baik','Rusak']]],columns:[['name','Fasilitas'],['standard','Standar'],['actual','Aktual'],['condition','Kondisi']]},
 maintenance:{title:'Maintenance',desc:'Preventive maintenance dan pemenuhan SLA tiket.',button:'Tambah Maintenance',fields:[['month','Bulan','select',[...monthNames,'-']],['scheduled','Jadwal PM','number'],['realized','Realisasi PM','number'],['ticket','No. Tiket','text'],['start','Tanggal Mulai','date'],['finish','Tanggal Selesai','date'],['sla','Standar SLA (hari)','number']],columns:[['month','Bulan'],['scheduled','Jadwal PM'],['realized','Realisasi PM'],['ticket','No. Tiket'],['start','Mulai'],['finish','Selesai'],['sla','SLA'],['_ticketStatus','Status']]},
 legality:{title:'Legalitas',desc:'Monitoring masa berlaku dan reminder perpanjangan 90 hari.',button:'Tambah Dokumen',fields:[['document','Dokumen','text'],['expiry','Tanggal Expire','date']],columns:[['document','Dokumen'],['expiry','Tanggal Expire'],['_legalStatus','Status'],['_reminder','Reminder']]},
 budgets:{title:'Budget Control',desc:'Monitoring budget, aktual, sisa, dan persentase pemakaian.',button:'Tambah Budget',fields:[['category','Kategori','text'],['budget','Budget','number'],['actual','Aktual','number']],columns:[['category','Kategori'],['budget','Budget'],['actual','Aktual'],['_usage','Pemakaian'],['_remaining','Sisa Budget']]},
 audits:{title:'Audit 5S Mingguan',desc:'Penilaian kebersihan, kerapihan, safety, dan kelayakan.',button:'Tambah Audit',fields:[['date','Tanggal','date'],['area','Area','text'],['auditor','Auditor','text'],['cleanliness','Kebersihan','number'],['tidiness','Kerapihan','number'],['lighting','Pencahayaan','number'],['air','AC / Ventilasi','number'],['safety','Keamanan','number'],['feasibility','Kelayakan','number'],['note','Catatan','textarea']],columns:[['date','Tanggal'],['area','Area'],['auditor','Auditor'],['_score','Score'],['note','Catatan']]}
};
const weights=[.1,.15,.15,.2,.1,.15,.05,.1],targets=[1,.95,.95,1,.95,1,1,.95];
const kpiNames=['Asset Management','Facility Availability','Condition of Facility','Preventive Maintenance','Corrective Maintenance','Legal Compliance','Budget Control','5S Weekly Audit'];
const fmtPercent=v=>`${(Number(v||0)*100).toFixed(1)}%`,fmtMoney=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v||0);
const dayDiff=(a,b)=>Math.ceil((new Date(b)-new Date(a))/86400000);
function calculations(record=state){
 const assets=record.assets,fac=record.facilities,maint=record.maintenance,legal=record.legality,budget=record.budgets,audits=record.audits;
 const today=new Date();today.setHours(0,0,0,0);
 const assetScore=assets.length?assets.filter(x=>x.status==='Sesuai').length/assets.length:0;
 const facilityAvail=fac.reduce((s,x)=>s+Number(x.standard||0),0)?fac.reduce((s,x)=>s+Number(x.actual||0),0)/fac.reduce((s,x)=>s+Number(x.standard||0),0):0;
 const facilityCondition=fac.length?fac.filter(x=>x.condition==='Baik').length/fac.length:0;
 const pmScheduled=maint.reduce((s,x)=>s+Number(x.scheduled||0),0),pmRealized=maint.reduce((s,x)=>s+Number(x.realized||0),0);
 const pm=pmScheduled?pmRealized/pmScheduled:0;
 const closed=maint.filter(x=>x.finish),slaCount=closed.filter(x=>dayDiff(x.start,x.finish)<=Number(x.sla)).length,corrective=closed.length?slaCount/closed.length:0;
 const valid=legal.filter(x=>new Date(x.expiry)>today).length,legalScore=legal.length?valid/legal.length:0;
 const totalBudget=budget.reduce((s,x)=>s+Number(x.budget||0),0),actualBudget=budget.reduce((s,x)=>s+Number(x.actual||0),0),budgetUsage=totalBudget?actualBudget/totalBudget:0,budgetScore=totalBudget?(budgetUsage<=.9?1:0):0;
 const auditScores=audits.map(a=>['cleanliness','tidiness','lighting','air','safety','feasibility'].reduce((s,k)=>s+Number(a[k]||0),0)/600),auditScore=auditScores.length?auditScores.reduce((a,b)=>a+b,0)/auditScores.length:0;
 const actuals=[assetScore,facilityAvail,facilityCondition,pm,corrective,legalScore,budgetScore,auditScore];
 const contribution=actuals.map((a,i)=>targets[i]?a/targets[i]*weights[i]:0),total=contribution.reduce((a,b)=>a+b,0);
 return{actuals,contribution,total,totalBudget,actualBudget,budgetUsage,remaining:totalBudget-actualBudget,assetBroken:assets.filter(x=>x.condition==='Rusak').length,openTickets:maint.filter(x=>!x.finish).length,expiring:legal.filter(x=>{const d=dayDiff(today,x.expiry);return d>=0&&d<=90}).length,expired:legal.filter(x=>new Date(x.expiry)<=today).length,auditScores};
}
function status(v){return v>=1?'green':v>=.9?'yellow':'red'}function statusLabel(v){return v>=1?'Baik':v>=.9?'Cukup':'Buruk'}
function setSaveState(text,type='local'){const box=document.querySelector('#saveState'),label=document.querySelector('#saveStateText');if(!box||!label)return;box.classList.remove('syncing','cloud-error','cloud-ok');if(type)box.classList.add(type);label.textContent=text}
function save(){store.records[store.selectedSppg]??={};store.records[store.selectedSppg][store.selectedPeriod]=state;localStorage.setItem('gaKpiStore',JSON.stringify(store));if(window.KpiCloud?.enabled()){setSaveState('Menyimpan ke cloud...','syncing');window.KpiCloud.save(store).then(()=>setSaveState('Tersambung ke cloud','cloud-ok')).catch(error=>{console.error(error);setSaveState('Cloud gagal · tersimpan lokal','cloud-error')})}else setSaveState('Tersimpan di perangkat ini','local')}
function switchDataset(name,period){save();store.selectedSppg=name;store.selectedPeriod=period;state=getRecord(name,period);state.meta={sppg:name,period};document.querySelector('#periodInput').value=period;save();render()}
function switchSppg(name){switchDataset(name,store.selectedPeriod)}
function switchPeriod(period){switchDataset(store.selectedSppg,period)}
function pageHead(title,desc,button=''){return `<div class="page-head"><div><small>KPI GENERAL AFFAIR</small><h1>${title}</h1><p>${desc}</p></div>${button?`<button class="btn primary" data-add>＋ ${button}</button>`:''}</div>`}
function dashboard(){
 const c=calculations();const top=c.actuals.indexOf(Math.max(...c.actuals)),low=c.actuals.indexOf(Math.min(...c.actuals));
 const rows=kpiNames.map((name,i)=>`<tr><td>${name}</td><td>${fmtPercent(targets[i])}</td><td>${fmtPercent(weights[i])}</td><td>${fmtPercent(c.actuals[i])}</td><td>${fmtPercent(c.contribution[i])}</td><td><span class="status ${status(c.actuals[i])}">${statusLabel(c.actuals[i])}</span></td></tr>`).join('');
 return `${pageHead('Executive Dashboard',`Ringkasan KPI ${state.meta.sppg} · ${periodLabel()}`)}<div class="summary-grid"><article class="summary-card accent"><small>Total KPI</small><strong>${fmtPercent(c.total)}</strong><div class="hint">Akumulasi kontribusi berbobot</div></article><article class="summary-card"><small>KPI Tertinggi</small><strong style="font-size:16px">${kpiNames[top]}</strong><div class="hint">${fmtPercent(c.actuals[top])}</div></article><article class="summary-card"><small>KPI Terendah</small><strong style="font-size:16px">${kpiNames[low]}</strong><div class="hint">${fmtPercent(c.actuals[low])}</div></article><article class="summary-card"><small>Sisa Budget</small><strong style="font-size:17px">${fmtMoney(c.remaining)}</strong><div class="hint">Dari ${fmtMoney(c.totalBudget)}</div></article></div><div class="dashboard-grid"><article class="panel"><div class="panel-title"><h2>Pencapaian KPI</h2><small>Traffic light otomatis</small></div><div class="table-scroll"><table class="kpi-table"><thead><tr><th>KPI</th><th>Target</th><th>Bobot</th><th>Aktual</th><th>Ach KPI</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table></div></article><article class="panel score-panel"><div><div class="panel-title"><h2>Distribusi Status</h2></div><div class="score-visual"><div class="donut"><div class="donut-label"><strong>${fmtPercent(c.total)}</strong><small>TOTAL KPI</small></div></div><div class="legend"><span><i style="background:var(--green)"></i>Baik ${c.actuals.filter(x=>x>=1).length}</span><span><i style="background:var(--yellow)"></i>Cukup ${c.actuals.filter(x=>x>=.9&&x<1).length}</span><span><i style="background:var(--red)"></i>Buruk ${c.actuals.filter(x=>x<.9).length}</span></div></div></div><div class="quick-grid"><div class="quick-item"><small>Asset Rusak</small><strong>${c.assetBroken}</strong></div><div class="quick-item"><small>Open Ticket</small><strong>${c.openTickets}</strong></div><div class="quick-item"><small>Expire ≤90 Hari</small><strong>${c.expiring}</strong></div><div class="quick-item"><small>Budget Terpakai</small><strong>${fmtPercent(c.budgetUsage)}</strong></div></div></article></div>`;
}
function cellValue(row,key,index){const c=calculations();if(key==='_ticketStatus')return row.finish?(dayDiff(row.start,row.finish)<=Number(row.sla)?'SLA':'Overdue'):'Open';if(key==='_legalStatus')return new Date(row.expiry)>new Date()?'VALID':'EXPIRED';if(key==='_reminder'){const d=dayDiff(new Date(),row.expiry);return d<=90?'RENEW':'OK'}if(key==='_usage')return fmtPercent(Number(row.actual)/Number(row.budget));if(key==='_remaining')return fmtMoney(Number(row.budget)-Number(row.actual));if(key==='_score')return fmtPercent(c.auditScores[index]);if(currentPage==='budgets'&&['budget','actual'].includes(key))return fmtMoney(row[key]);return row[key]??'-'}
function modulePage(key){const s=schemas[key],c=calculations(),stats={assets:[['Akurasi SO',fmtPercent(c.actuals[0])],['Asset Rusak',c.assetBroken]],facilities:[['Kelengkapan',fmtPercent(c.actuals[1])],['Kondisi Baik',fmtPercent(c.actuals[2])]],maintenance:[['PM Compliance',fmtPercent(c.actuals[3])],['SLA Compliance',fmtPercent(c.actuals[4])],['Open Ticket',c.openTickets]],legality:[['Compliance',fmtPercent(c.actuals[5])],['Renew ≤90 Hari',c.expiring],['Expired',c.expired]],budgets:[['Pemakaian',fmtPercent(c.budgetUsage)],['Sisa',fmtMoney(c.remaining)]],audits:[['Rata-rata Audit',fmtPercent(c.actuals[7])],['Jumlah Audit',state.audits.length]]}[key];const head=s.columns.map(x=>`<th>${x[1]}</th>`).join('');const rows=state[key].map((row,i)=>`<tr>${s.columns.map(x=>`<td>${cellValue(row,x[0],i)}</td>`).join('')}<td><div class="row-actions"><button class="icon-btn edit" data-edit="${i}">Edit</button><button class="icon-btn delete" data-delete="${i}">Hapus</button></div></td></tr>`).join('');return `${pageHead(s.title,s.desc,s.button)}<div class="module-stats">${stats.map(x=>`<div class="module-stat"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('')}</div><div class="data-panel"><div class="table-scroll"><table class="data-table"><thead><tr>${head}<th>Aksi</th></tr></thead><tbody>${rows}</tbody></table>${rows?'':'<div class="empty">Belum ada data. Klik tombol tambah untuk mulai mengisi.</div>'}</div></div>`}
function trendPage(){const colors=['#16716f','#279b77','#73b84f','#dfaa2f','#e7782b','#c94e47','#7b58b5','#436fb0'];const records=store.records[store.selectedSppg]||{};const data=Object.entries(records).sort(([a],[b])=>a.localeCompare(b)).slice(-12).map(([period,record])=>({period,label:periodLabelFrom(period),values:calculations(record).actuals}));const bars=data.map(m=>`<div class="trend-month has-labels">${m.values.map((v,i)=>`<i title="${kpiNames[i]}: ${fmtPercent(v)}" style="height:${Math.min(v,1)*100}%;background:${colors[i]}"></i>`).join('')}<span>${m.label}</span></div>`).join('');const headers=data.map(m=>`<th>${m.label}</th>`).join('');const values=kpiNames.map((name,i)=>`<tr><td><i style="display:inline-block;width:8px;height:8px;border-radius:50%;background:${colors[i]};margin-right:6px"></i>${name}</td>${data.map(m=>`<td>${fmtPercent(m.values[i])}</td>`).join('')}</tr>`).join('');return `${pageHead('Tren Bulanan',`Pencapaian KPI bulanan untuk ${store.selectedSppg}.`)}<article class="panel"><div class="panel-title"><h2>Trend KPI 12 Bulan</h2><small>Skala 0–100%</small></div>${data.length?`<div class="trend-bars">${bars}</div><div class="legend" style="flex-wrap:wrap;margin-top:18px">${kpiNames.map((n,i)=>`<span><i style="background:${colors[i]}"></i>${n}</span>`).join('')}</div><div class="table-scroll trend-values"><table class="data-table"><thead><tr><th>Indikator KPI</th>${headers}</tr></thead><tbody>${values}</tbody></table></div>`:'<div class="empty">Belum ada rekaman bulanan untuk SPPG ini.</div>'}</article>`}
function periodLabelFrom(period){if(!period)return'-';const [y,m]=period.split('-');return `${monthNames[Number(m)-1]} ${y}`}
function periodLabel(){return periodLabelFrom(state.meta.period)}
function sppgAssetCode(name){const number=(name.match(/\d+/)||[])[0],clean=name.replace(/\d+/g,'').replace(/\./g,'').trim(),words=clean.split(/\s+/).filter(Boolean);if(number){const letters=words.length>1?(words[0][0]+words[1][0]):words[0].slice(0,2);return `${letters.toUpperCase()}${number}`}return words.join('').slice(0,3).toUpperCase()}
function nextAssetNumber(){const allMonths=Object.values(store.records[store.selectedSppg]||{}),used=allMonths.flatMap(record=>record.assets||[]).map(asset=>Number((String(asset.assetNo||'').match(/(\d+)$/)||[])[1]||0)),next=(Math.max(0,...used)+1).toString().padStart(3,'0');return `AST-PURI-${sppgAssetCode(store.selectedSppg)}-${next}`}
function render(){const content=document.querySelector('#content');content.innerHTML=currentPage==='dashboard'?dashboard():currentPage==='trend'?trendPage():modulePage(currentPage);content.querySelector('[data-add]')?.addEventListener('click',()=>openDialog());content.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>openDialog(Number(b.dataset.edit))));content.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>deleteRow(Number(b.dataset.delete))));}
function openDialog(index=null){editingIndex=index;const schema=schemas[currentPage],row=index===null?{}:state[currentPage][index];if(currentPage==='assets'&&index===null)row.assetNo=nextAssetNumber();document.querySelector('#dialogTitle').textContent=`${index===null?'Tambah':'Edit'} ${schema.title}`;document.querySelector('#formFields').innerHTML=schema.fields.map(([key,label,type,options])=>`<div class="form-field ${type==='textarea'?'full':''}"><label for="f-${key}">${label}</label>${type==='select'?`<select id="f-${key}" name="${key}" required><option value="">Pilih ${label}</option>${options.map(o=>`<option ${row[key]===o?'selected':''}>${o}</option>`).join('')}</select>`:type==='textarea'?`<textarea id="f-${key}" name="${key}">${row[key]||''}</textarea>`:`<input id="f-${key}" name="${key}" type="${type==='auto'?'text':type}" value="${row[key]??''}" ${type==='number'?'min="0" step="any"':''} ${type==='auto'?'readonly aria-readonly="true"':''} required>`}</div>`).join('');document.querySelector('#entryDialog').showModal()}
function deleteRow(index){if(confirm('Hapus data ini?')){state[currentPage].splice(index,1);save();render()}}
document.querySelector('#entryForm').addEventListener('submit',e=>{e.preventDefault();const schema=schemas[currentPage],data=Object.fromEntries(new FormData(e.target));schema.fields.forEach(([key,,type])=>{if(type==='number')data[key]=Number(data[key])});if(editingIndex===null)state[currentPage].push(data);else state[currentPage][editingIndex]=data;save();document.querySelector('#entryDialog').close();render()});
document.querySelectorAll('.nav-item[data-page]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');currentPage=btn.dataset.page;render();closeMenu()}));
const sppgInput=document.querySelector('#sppgInput');sppgInput.innerHTML=sppgNames.map(name=>`<option value="${name}">${name}</option>`).join('');sppgInput.value=store.selectedSppg;document.querySelector('#periodInput').value=store.selectedPeriod;sppgInput.addEventListener('change',e=>switchSppg(e.target.value));document.querySelector('#periodInput').addEventListener('change',e=>switchPeriod(e.target.value));
['closeDialog','cancelDialog'].forEach(id=>document.querySelector(`#${id}`).addEventListener('click',()=>document.querySelector('#entryDialog').close()));
document.querySelector('#backupButton').addEventListener('click',()=>{save();const blob=new Blob([JSON.stringify(store,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='backup-kpi-ga-semua-sppg.json';a.click();URL.revokeObjectURL(a.href)});
document.querySelector('#restoreButton').addEventListener('click',()=>document.querySelector('#restoreInput').click());
document.querySelector('#restoreInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const restored=JSON.parse(await file.text());if(!restored.records||!restored.selectedSppg)throw new Error('Format tidak sesuai');store=restored;store.selectedPeriod=store.selectedPeriod||new Date().toISOString().slice(0,7);state=getRecord(store.selectedSppg,store.selectedPeriod);save();sppgInput.value=store.selectedSppg;document.querySelector('#periodInput').value=store.selectedPeriod;currentPage='dashboard';render();alert('Backup berhasil dipulihkan.')}catch{alert('File backup tidak valid.')}e.target.value=''});
const sidebar=document.querySelector('#sidebar'),backdrop=document.querySelector('#backdrop');function closeMenu(){sidebar.classList.remove('open');backdrop.classList.remove('show')}document.querySelector('#menuButton').addEventListener('click',()=>{sidebar.classList.toggle('open');backdrop.classList.toggle('show')});backdrop.addEventListener('click',closeMenu);
async function initializeApp(){if(window.KpiCloud?.enabled()){setSaveState('Menghubungkan ke cloud...','syncing');try{const remote=await window.KpiCloud.load();if(remote?.records){store=remote;if(!sppgNames.includes(store.selectedSppg))store.selectedSppg=sppgNames[0];store.selectedPeriod=store.selectedPeriod||new Date().toISOString().slice(0,7);state=getRecord(store.selectedSppg,store.selectedPeriod);localStorage.setItem('gaKpiStore',JSON.stringify(store))}sppgInput.value=store.selectedSppg;document.querySelector('#periodInput').value=store.selectedPeriod;render();if(remote)setSaveState('Tersambung ke cloud','cloud-ok');else save()}catch(error){console.error(error);render();setSaveState('Cloud gagal · memakai data lokal','cloud-error')}}else{render();setSaveState('Tersimpan di perangkat ini','local')}}
initializeApp();
